package com.smartcampus.backend.booking.model;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Positive;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


@Data

// Marks this class as a MongoDB document (collection name = "bookings")
@Document(collection = "bookings")
public class Booking {

    // Unique ID for each booking (automatically generated by MongoDB)
    @Id
    private String id;

    // ID of the resource being booked (e.g., lab, room, equipment)
    @NotBlank(message = "Resource ID is required")
    private String resourceId;

    // ID of the user who made the booking
    @NotBlank(message = "User ID is required")
    private String userId;

    // Booking date (e.g., 2026-04-12)
    @NotBlank(message = "Date is required")
    private String date;

    // Start time of the booking (e.g., 10:00 AM)
    @NotBlank(message = "Start time is required")
    private String startTime;

    // End time of the booking (e.g., 12:00 PM)
    @NotBlank(message = "End time is required")
    private String endTime;

    // Purpose of the booking (why the resource is needed)
    @NotBlank(message = "Purpose is required")
    private String purpose;

    // Number of people attending (must be greater than 0)
    @Positive(message = "Attendees must be greater than 0")
    private int attendees;

    // Current status of the booking

    private String status;

    // Reason for approval or rejection (set by admin)
    private String reviewReason;

    // ID or name of the admin who approved/rejected the booking
    private String approvedBy;
}